name: Run ETL Job

on:
  workflow_dispatch:   # Manual trigger button
  push:                # Runs when you push code
    branches:
      - main
  schedule:            # Daily schedule at 2 AM UTC
    - cron: "0 2 * * *"

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: List repo files
        run: ls-R  
      
      - name: Run ETL script
        run: python etl.py