name: CI/CD Data Pipeline

on:
    push:
        branches:
            - main       # Trigger workflow when pushing to main
    workflow_dispatch:   # Allow manual trigger
#    schedule:
#        - cron: "0 8 * * *"

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        services:
          postgres:
            image: postgres:17

            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: postgres

            ports:
              - 5432:5432

            options: >-
              --health-cmd "pg_isready -U postgres -d postgres"
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
        
        env:
          CONNECTION_URL: postgresql://postgres:postgres@localhost:5432/postgres

        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
        
          - name: Set Up Python
            uses: actions/setup-python@v4
            with:
              python-version: "3.14"
          
          - name: Install Dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt 

          - name: Run Tests
            run: |
              pip show pytest || pip install pytest
              pytest --disable-warnings

    Deploy:
        needs: build-and-test
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'  # Only deploy from main branch

        services:
          postgres:
            image: postgres:17

            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: postgres

            ports:
              - 5432:5432

            options: >-
              --health-cmd "pg_isready -U postgres -d postgres"
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
        
        env:
          CONNECTION_URL: postgresql://postgres:postgres@localhost:5432/postgres

        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
          
          - name: Set Up Python
            uses: actions/setup-python@v4
            with:
              python-version: "3.14"

          - name: Install Dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
                        
          - name: Deploying To Production..
            run: |
              echo "Deploying ETL job..."
              python etl.py